{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}
spec:
  type: {{ .Values.service.type  }}
  selector:
    app.kubernetes.io/name: {{ include "<CHART_NAME>.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ required "Port is required" .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}

{{- end }}
