{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include " <CHART_NAME>.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include " <CHART_NAME>.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ required "Port is required" .Values.service.port }}
      targetPort: {{ required "TargetPort is required" .Values.service.targetPort default 8080 }}
{{- end }}
